
language: android

android:
  components:
    - build-tools-21.1.2
    - android-21
    - android-14
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-14

env:
  matrix:
    - ANDROID_VERSION=14
    - ANDROID_VERSION=21

before_script:
  - echo no | android create avd --force -n test$ANDROID_VERSION -t android-$ANDROID_VERSION --abi default/armeabi-v7a
  - emulator -avd test$ANDROID_VERSION -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
